# Generated by Django 4.2.26 on 2025-11-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('summary_data', models.JSONField()),
                ('original_file', models.FileField(blank=True, null=True, upload_to='csv_uploads/')),
            ],
        ),
    ]
